# -*- coding: utf-8 -*-
"""LVADSUSR97_Lokesh_A_lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BiiEHf3RG-B_7KH1FQ4NYggTJmBZfFYU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import tree
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

dat=pd.read_csv("/content/sample_data/booking.csv")
dat

dat.isnull().sum()

dat.dropna()

label_encoder=LabelEncoder()
dat['type of meal']=label_encoder.fit_transform(dat['type of meal'])
dat['room type']=label_encoder.fit_transform(dat['room type'])
dat['market segment type']=label_encoder.fit_transform(dat['market segment type'])
dat['booking status']=label_encoder.fit_transform(dat['booking status'])
dat

x=dat.drop(columns=['booking status','Booking_ID','date of reservation'])
y=dat.iloc[:,-1:]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)

model_var=tree.DecisionTreeClassifier()
model_var=model_var.fit(x_train,y_train)
model_prediction=model_var.predict(x_test)
print(model_prediction)
mse=mean_squared_error(model_prediction,y_test)
print("the mse is",mse)
mae=mean_absolute_error(model_prediction,y_test)
print("the mae is",mae)
model_accuracy=accuracy_score(model_prediction,y_test)
print("the model accuracy is ",model_accuracy)

from sklearn.metrics import confusion_matrix

conf_matrix=confusion_matrix(model_prediction,y_test)
print(conf_matrix)